# Generated by Django 2.2.7 on 2021-06-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55)),
                ('details', models.TextField(blank=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
